name: ARM 64 Python application

on:
  push:
    paths:
    - 'python/*'
      
jobs:
  build:
    #runs-on: ubuntu-24.04-arm64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64
    - name: Set up Python 3.9.21
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.21
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: wodge
        password: ${{ secrets.WODGE_SECRET }}
    # - name: Build and push
    #   uses: docker/build-push-action@v2
    #   with:
    #     platforms: linux/arm64
    #     push: true
    #     tags: wodge/gitops:hello-arm64-v1.4
    - name: Build & Push Image
      run: |
        cd ./python
        echo "${{ secrets.WODGE_SECRET }}" | docker login -u "wodge" --password-stdin
        docker buildx build --platform linux/arm64 -t wodge/gitops:hello-arm64-v1.5 .
        docker push wodge/gitops:hello-arm64-v1.5
