name: Python application

on:
  push:
    paths:
    - 'python/*'
      
jobs:
  build:
    #runs-on: ubuntu-latest-arm64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9.21
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.21
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Build & Push Image
      run: |
        cd ./python
        echo "${{ secrets.WODGE_SECRET }}" | docker login -u "wodge" --password-stdin
        docker image build -t wodge/gitops:hellov1.3 .
        wodge/gitops:hellov1.3
        docker push wodge/gitops:hellov1.3
