apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello
    app.kubernetes.io/instance: hello
  name: svc-hello
  namespace: lasample
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: hello
status:
  loadBalancer: {}